version: '3'
services:
  backend:
    build: ./myproject  # Pfad zum Django-Projekt
    ports:
      - "8080:8080"
    volumes:
      - ./myproject:/app
    environment:
      - DEBUG=True

  frontend:
    build: ./my-solid-app  # Pfad zum Solid.js-Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
